# Generated by Django 4.1.7 on 2023-04-10 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0007_remove_video_title_video_caption_alter_video_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(default='', upload_to='upload_video/'),
        ),
    ]
